
[build-system]
# Note that running tests additionally requires pytest and pydataset, but they are not
# required for building the package. See tox.ini for test-time dependencies.
requires = ["setuptools>=62", "wheel", "setuptools_scm~=7.0.3"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]

[project]
name = "frankenfit"
version = "0.1"
authors = [
    {name = "Max Bane", email = "max@thebanes.org"}
]
requires-python = ">=3.9"
dependencies = [
    'attrs',
    'pandas',
    'pyarrow',
    'graphviz',
    'distributed',  # TODO: make this an optional feature dependency?
]

[tool.mypy]
plugins = "frankenfit.mypy"
