name: build-dist

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ vars.PY_VER_BUILD_TEST }}
      - name: Upgrade pip and build
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build
      - name: build
        run: |
          python -m build
      - name: upload-artifact
        uses: actions/upload-artifact@v3
        if: ${{ !env.ACT }}
        with:
          name: dist-files
          path: dist/
