name: mypy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  mypy:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Upgrade pip and install tox
        run: |
          python -m pip install --upgrade pip
          python -m pip install "tox < 4"
      - name: mypy
        run: tox -e mypy
