name: publish-testpypi

on:
  - workflow_dispatch
  - workflow_call

jobs:
  twine:
    runs-on: ubuntu-22.04
    environment: testpypi
    steps:
      - uses: actions/checkout@v3
      - name: call-build-dist
        uses: maxbane/frankenfit/.github/workflows/build-dist.yml@main
      - name: download dist-files
        uses: actions/download-artifact@v3
        with:
          name: dist-files
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ vars.PY_VER_BUILD_TEST }}
      - name: Upgrade pip and twine
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade twine
      - name: twine upload
        env:
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
          TWINE_REPOSITORY: ${{ vars.TWINE_REPOSITORY }}
          TWINE_NON_INTERACTIVE: "y"
        run: |
          ls -l dist/*
          echo "TWINE_REPOSITORY: $TWINE_REPOSITORY"
          # python -m twine upload -u __token__
