name: Frankenfit CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  linters:
    name: Linters
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Upgrade pip and install tox
        run: |
          python -m pip install --upgrade pip
          python -m pip install "tox < 4"
      - name: linters
        run: tox -p -e flake8,black

  unit_tests:
    name: Unit tests
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Upgrade pip and install tox
        run: |
          python -m pip install --upgrade pip
          python -m pip install "tox < 4"
      - name: pytest
        # Run tox using the version of Python in `PATH`
        run: tox -e py

  typechecker:
    name: Type checker (mypy)
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Upgrade pip and install tox
        run: |
          python -m pip install --upgrade pip
          python -m pip install "tox < 4"
      - name: mypy
        run: tox -e mypy

  docs:
    name: Documentation
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Upgrade pip and install tox
        run: |
          python -m pip install --upgrade pip
          python -m pip install "tox < 4"
      - name: jupyter-book
        run: tox -e docs
      - name: upload
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v3
        with:
          name: frankenfit-docs-html
          path: docs/_build/html
