name: Frankenfit CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  linters:
    name: Linters
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Upgrade pip and install tox
        run: |
          python -m pip install --upgrade pip
          python -m pip install "tox < 4"
      - name: linters
        run: tox -e pre-commit

  unit_tests:
    name: Unit tests
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Upgrade pip and install tox
        run: |
          python -m pip install --upgrade pip
          python -m pip install "tox < 4"
      - name: pytest
        # Run tox using the version of Python in `PATH`
        run: tox -e py

  typechecker:
    name: Type checker (mypy)
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Upgrade pip and install tox
        run: |
          python -m pip install --upgrade pip
          python -m pip install "tox < 4"
      - name: mypy
        run: tox -e mypy

  docs:
    name: Documentation
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Upgrade pip and install tox
        run: |
          python -m pip install --upgrade pip
          python -m pip install "tox < 4"
      - name: jupyter-book
        run: tox -e docs
      - name: upload-logs-on-failure
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: frankenfit-docs-html-reports
          path: docs/_build/html/reports/
      - name: upload-artifact
        uses: actions/upload-artifact@v3
        if: ${{ !env.ACT }}
        with:
          name: frankenfit-docs-html
          path: docs/_build/html/
      - name: deploy-current-docs
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' && !env.ACT }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
          destination_dir: current
          commit_message: |
            Deploy current docs: ${{ github.event.head_commit.message }}
